apiVersion: v1
kind: Service
metadata:
  name: openbikeshare-front
  labels:
    app: openbikeshare-front
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: openbikeshare-front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbikeshare-front
  labels:
    app: openbikeshare-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbikeshare-front
  template:
    metadata:
      labels:
        app: openbikeshare-front
    spec:
      containers:
      - name: fleet
        image: docker.pkg.github.com/openbikeshare/map/front:1.0
      imagePullSecrets:
      - name: regcred-github-openbike

